### ISSUE TITLE
Resolve ignored interpolation errors in AGSOutputs

### ISSUE THREAD

**Issue by softwareengineerprogrammer** [NREL/python-geophires-x#7]
https://github.com/NREL/python-geophires-x/blob/d821f871219b5aba35da9323a3443988a3a56b94/src/geophires_x/AGSOutputs.py#L48-L62

**Comment by softwareengineerprogrammer** [comment]
Need input from @malcolm-dsider on whether ignoring errors is appropriate in the lines in question

**Comment by malcolm-dsider** [comment]
Is it failing on the line 52 and 56 or 54 and 58? I guess it doesn't really matter, because getting the interpolation done is important. Do you need me to search for another way to get the interpolation done? There is always another way to skin a cat. Should I look within numpy or outside?

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider to repro locally, change line 50 to:

```python
                with np.errstate(all='raise'):
```

and run unit tests. For me this causes the Beckers cases `Coaxial_sCO2_heat`, `Coaxial_water_heat`, `Uloop_sCO2_heat`, and `Uloop_water_heat` to fail (the only Beckers case that still passes is `Uloop_sCO2_elec`).

The criteria for resolving this, since the interpolation is apparently important to the correctness of the result, would be to get those cases passing without ignoring the error. I can't really speak to what the right way to accomplish that is (given my lack of domain expertise and familiarity with this particular area of the code) but finding another way to get it done sounds like a reasonable first foray.

**Comment by malcolm-dsider** [comment]
I think I see what is going on - all the tests that fail involve heat production ONLY, but the interpolate function is trying to interpolate the array model.surfaceplant.NetElectricityProduced.value while it is empty (only one value and that is [0]). It doesn't need to do this interpolation if it is running in heat-only mode. And it doesn't need to do the interpolation for model.surfaceplant.FirstLawEfficiency.value either, because First law Efficiency has to do with efficiency of conversion to electricity. So the fix is to put in an if statement that does the NetElectricityProduced and FirstLawEfficiency interpolation only if the product is electricity. Do you want me to do that? The easy thing to do is to execute the interpolation only if the len (NetElectricityProduced) and len(FirstLawEfficiency) are > 1, respectively.

**Comment by softwareengineerprogrammer** [comment]
@malcolm-dsider nice, great you were able to figure that out. Yes, please go ahead and create a PR if you're able, I'll keep an eye out.

**Comment by softwareengineerprogrammer** [comment]
PR is merged - thanks for fixing @malcolm-dsider!
